name: NodeJS with Webpack

on:
  push:
    tags:
      - cicd*

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      - run: echo "$$$$$$$ [ P R O D U C T I O N] $$$$$$$"

      - name: Checkout latest
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Execute tests
        run: |
          npm install
          npm run test

      - name: Build Webpack
        run: |
          npm install
          npm run build

      - name: Deploy Badges -> SFTP to Webspace
        uses: Dylan700/sftp-upload-action@latest
        with:
          server: ${{ secrets.SFTP_SERVER }}
          port: 22
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          uploads: |
            ./coverage/ => ${{ vars.PATH_WEBSPACE_BADGES }}
          ignore: |
            *.git
